[2010-03-23 21:52:02,704] INFO     0[main](AssertMain.java:17) - Results asserter starting
[2010-03-23 21:52:02,706]DEBUG     2[main](AssertMain.java:20) - Program arguments:
[2010-03-23 21:52:02,711]DEBUG     7[main](AssertMain.java:22) - args[0] 'cipher-throw-soapfaultexception-sin'
[2010-03-23 21:52:02,711]DEBUG     7[main](AssertMain.java:22) - args[1] 'D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin'
[2010-03-23 21:52:02,712]DEBUG     8[main](AssertMain.java:45) - Building context
[2010-03-23 21:52:02,727]TRACE    23[main](AssertMain.java:66) - Context:
[2010-03-23 21:52:02,728]TRACE    24[main](AssertMain.java:68) - resultDir: D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin
[2010-03-23 21:52:02,728]TRACE    24[main](AssertMain.java:68) - clientSoap: D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin\soap-trace-client.log
[2010-03-23 21:52:02,728]TRACE    24[main](AssertMain.java:68) - serverLog: D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin\log-server.log
[2010-03-23 21:52:02,729]TRACE    25[main](AssertMain.java:68) - config: cipher-throw-soapfaultexception-sin
[2010-03-23 21:52:02,729]TRACE    25[main](AssertMain.java:68) - serverSoap: D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin\soap-trace-server.log
[2010-03-23 21:52:02,729]TRACE    25[main](AssertMain.java:68) - clientLog: D:\dev\stepframework\src_test\extensions-testbed\results\20100323\2135\cipher-throw-soapfaultexception-sin\log-client.log
[2010-03-23 21:52:02,730]DEBUG    26[main](AssertMain.java:76) - Entering assert dispatch
[2010-03-23 21:52:02,730]DEBUG    26[main](AssertMain.java:79) - Asserting configuration 'cipher-throw-soapfaultexception-sin'
[2010-03-23 21:52:02,746] INFO    42[main](Assertions.java:52) - assertClientSOAPFaultException
[2010-03-23 21:52:02,767] INFO    63[main](Assertions.java:162) - assertSOAPCounts
[2010-03-23 21:52:02,767] INFO    63[main](Assertions.java:118) - assertCountClientSOAPEnvelopes
[2010-03-23 21:52:02,769] INFO    65[main](Assertions.java:123) - assertCountServerSOAPEnvelopes
[2010-03-23 21:52:02,769] INFO    65[main](Assertions.java:128) - assertCountClientSOAPFaults
[2010-03-23 21:52:02,770] INFO    66[main](Assertions.java:133) - assertCountServerSOAPFaults
[2010-03-23 21:52:02,770] INFO    66[main](Assertions.java:172) - assertSOAPBodyCipherCounts
[2010-03-23 21:52:02,771] INFO    67[main](Assertions.java:138) - assertCountClientSOAPBodyCipher
[2010-03-23 21:52:02,771] INFO    67[main](Assertions.java:143) - assertCountServerSOAPBodyCipher
[2010-03-23 21:52:02,772] INFO    68[main](AssertMain.java:234) - SUCCESS! All assertions executed successfully for configuration 'cipher-throw-soapfaultexception-sin'
[2010-03-23 21:52:02,772] INFO    68[main](AssertMain.java:37) - End of results asserter.
